version: '3'

services:
  postgres2:
    image: postgres:11-alpine
    restart: always
    environment: 
      - POSTGRES_USER=softdbd
      - POSTGRES_PASSWORD=softdbd
      - POSTGRES_DB=pg_garbage
      - POSTGRES_CONTAINER_NAME=postgres2
      - POSTGRES_PORT=13337
      - PGDATA=/var/lib/postgres/data
    ports: 
        - 13337:5432
    volumes:
        - ./data/postgres:/var/lib/postgresql/data
    networks: 
      - app-network

networks:
  app-network:
    driver: "bridge"


    
