version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
        - "18651:6379"
    volumes:
        - ./data:/data
    networks: 
        - app-network
      
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
        - REDIS_HOSTS=local:redis:6379
    ports:
        - "22119:8081"
    networks: 
        - app-network
      
  backend:
    build:
        context: ./redis_teaching_demo
        dockerfile: dockerfile
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_DB=0
        - CONTAINERIZED_VARIABLES=1
    networks: 
        - app-network
    ports:
        - "5000:5000"

networks:
    app-network:
      driver: "bridge"
          