[package]
name = "task_3"
version = "0.1.0"
authors = ["Apathy <none-of@your.business>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"