import os

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(ROOT_DIR)

# The concept of public, private, protected, etc isn't supported in Python.
# You¨ll find, that some people use double underscore to represent private and single underscore to represent protected.
# I find, however, that most people just write a single underscore for private instead, and skip protected all together.
# In this assignment, private is represented by a single underscore.
_REGIONAL_BASE_PATH = ROOT_DIR + "/resources/Regionalt_DB/"
_COMMUNAL_BASE_PATH = ROOT_DIR + "/resources/Kommunalt_DB/"
CUSTOM_IMAGES_PATH = ROOT_DIR + "/resources/generated_images/"
CUSTOM_EXCEL_PATH = ROOT_DIR + "/resources/excel/"

REGIONAL_FILE_TREE = {
    "noegle_tal": _REGIONAL_BASE_PATH+"01_noegle_tal.csv",
    "hospital_belaegning": _REGIONAL_BASE_PATH+"02_hospitalsbelaegning.csv",
    "bekraeftede_tilfaelde_doede_indlagte_pr_dag_pr_koen": _REGIONAL_BASE_PATH+"03_bekraeftede_tilfaelde_doede_indlagte_pr_dag_pr_koen.csv",
    "indlagte_pr_alders_grp_pr_region": _REGIONAL_BASE_PATH+"04_indlagte_pr_alders_grp_pr_region.csv",
    "bekraeftede_tilfaelde_doede_pr_region_pr_alders_grp": _REGIONAL_BASE_PATH+"05_bekraeftede_tilfaelde_doede_pr_region_pr_alders_grp.csv",
    "nye_indlaeggelser_pr_region_pr_dag": _REGIONAL_BASE_PATH+"06_nye_indlaeggelser_pr_region_pr_dag.csv",
    "antal_doede_pr_dag_pr_region": _REGIONAL_BASE_PATH+"07_antal_doede_pr_dag_pr_region.csv",
    "bekraeftede_tilfaelde_pr_dag_pr_regions": _REGIONAL_BASE_PATH+"08_bekraeftede_tilfaelde_pr_dag_pr_regions.csv",
    "bekraeftede_tilfaelde_pr_test_region_pr_uge": _REGIONAL_BASE_PATH+"09_bekraeftede_tilfaelde_pr_test_region_pr_uge.csv",
    "testede_pr_uge_pr_samfundsspor_opgjort_paa_bopaelsregion": _REGIONAL_BASE_PATH+"10_testede_pr_uge_pr_samfundsspor_opgjort_paa_bopaelsregion.csv",
    "noegletal_pr_region_pr_aldersgruppe": _REGIONAL_BASE_PATH+"11_noegletal_pr_region_pr_aldersgruppe.csv",
    "noegletal_pr_region_pr_aldersgruppe_de_seneste_7_dage": _REGIONAL_BASE_PATH+"12_noegletal_pr_region_pr_aldersgruppe_de_seneste_7_dage.csv",
    "noegletal_pr_region_pr_aldersgruppe_de_seneste_7_dage": _REGIONAL_BASE_PATH+"12_noegletal_pr_region_pr_aldersgruppe_de_seneste_7_dage.csv",
    "regionale_kort": _REGIONAL_BASE_PATH+"13_regionale_kort.csv",
    "testede_pr_test_region_pr_uge": _REGIONAL_BASE_PATH+"14_testede_pr_test_region_pr_uge.csv",
    "indlagte_pr_region_pr_dag": _REGIONAL_BASE_PATH+"15_indlagte_pr_region_pr_dag.csv",
    "pcr_og_antigen_test_pr_region": _REGIONAL_BASE_PATH+"16_pcr_og_antigen_test_pr_region.csv"
}

COMMUNAL_FILE_TREE = {
    "noegletal": _COMMUNAL_BASE_PATH+"01_noegletal.csv",
    "indlaeggelser_pr_dag_kummulativt": _COMMUNAL_BASE_PATH+"02_indlaeggelser_pr_dag_kummulativt.csv",
    "indlaeggelser_pr_aldersgrp": _COMMUNAL_BASE_PATH+"03_indl├жggelser_pr_aldersgrp.csv",
    "bekraeftede_tilfaelde_doed_pr_aldersgrp": _COMMUNAL_BASE_PATH+"04_bekraeftede_tilfaelde_doed_pr_aldersgrp.csv",
    "nye_indlaeggelser_pr_dag": _COMMUNAL_BASE_PATH+"05_nye_indlaeggelser_pr_dag.csv",
    "doed_pr_dag_kumuleret": _COMMUNAL_BASE_PATH+"06_doed_pr_dag_kumuleret.csv",
    "bekraeftede_tilfaelde_pr_dag_pr_kommune": _COMMUNAL_BASE_PATH+"07_bekraeftede_tilfaelde_pr_dag_pr_kommune.csv",
    "proever_pr_uge_pr_region": _COMMUNAL_BASE_PATH+"08_proever_pr_uge_pr_region.csv",
    "tilfaelde_aldersgrp_kommuner": _COMMUNAL_BASE_PATH+"09_tilfaelde_aldersgrp_kommuner.csv",
    "kort_pr_kommune": _COMMUNAL_BASE_PATH+"10_kort_pr_kommune.csv",
    "pcr_og_antigen_test_pr_kommune": _COMMUNAL_BASE_PATH+"11_pcr_og_antigen_test_pr_kommune.csv",
    "mistaenkte_pos_pr_kommune_pr_dag": _COMMUNAL_BASE_PATH+"12_mistaenkte_pos_pr_kommune_pr_dag.csv"
}


LAU_CODES = {
    "Copenhagen": "101",
    "Aarhus": "751",
    "Aalborg": "851",
    "Odense": "461",
    "Esbjerg": "561",
    "Vejle": "630",
    "Frederiksberg": "147",
    "Randers": "730",
    "Viborg": "791",
    "Kolding": "621",
    "Silkeborg": "740",
    "Herning": "657",
    "Horsens": "615",
    "Roskilde": "265",
    "Næstved": "370",
    "Slagelse": "330",
    "Sønderborg": "540",
    "Gentofte": "157",
    "Holbæk": "316",
    "Hjørring": "860",
    "Gladsaxe": "159",
    "Guldborgsund": "376",
    "Helsingør": "217",
    "Frederikshavn": "813",
    "Aabenraa": "580",
    "Svendborg": "479",
    "Skanderborg": "746",
    "Ringkøbing-Skjern": "760",
    "Køge": "259",
    "Holstebro": "661",
    "Haderslev": "510",
    "Rudersdal": "230",
    "Lyngby-Taarbæk": "173",
    "Faaborg-Midtfyn": "430",
    "Hvidovre": "167",
    "Varde": "573",
    "Fredericia": "607",
    "Kalundborg": "326",
    "Hillerød": "219",
    "Høje-Taastrup": "169",
    "Ballerup": "151",
    "Greve": "253",
    "Skive": "779",
    "Favrskov": "710",
    "Hedensted": "766",
    "Vordingborg": "390",
    "Lolland": "360",
    "Thisted": "787",
    "Frederikssund": "250",
    "Vejen": "575",
    "Mariagerfjord": "846",
    "Egedal": "240",
    "Syddjurs": "706",
    "Assens": "420",
    "Bornholm": "400",
    "Tårnby": "185",
    "Ikast-Brande": "756",
    "Gribskov": "270",
    "Fredensborg": "210",
    "Tønder": "550",
    "Jammerbugt": "849",
    "Furesø": "190",
    "Norddjurs": "707",
    "Middelfart": "410",
    "Vesthimmerland": "820",
    "Rødovre": "175",
    "Brønderslev": "810",
    "Faxe": "320",
    "Brøndby": "153",
    "Ringsted": "329",
    "Odsherred": "306",
    "Nyborg": "450",
    "Halsnæs": "260",
    "Sorø": "340",
    "Nordfyn": "480",
    "Rebild": "840",
    "Albertslund": "165",
    "Lejre": "350",
    "Herlev": "163",
    "Billund": "530",
    "Hørsholm": "223",
    "Allerød": "201",
    "Kerteminde": "440",
    "Struer": "671",
    "Stevns": "336",
    "Odder": "727",
    "Glostrup": "161",
    "Morsø": "773",
    "Lemvig": "665",
    "Solrød": "269",
    "Ishøj": "183",
    "Vallensbæk": "187",
    "Dragør": "155",
    "Langeland": "482",
    "Ærø": "492",
    "Samsø": "741",
    "Fanø": "563",
    "Læsø": "825",
}
