[package]
name = "column_db"
version = "0.1.0"
authors = ["Apathy <none-of@your.business>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6"
fasthash = "0.4.0"
indoc="1.0.3"